# Parameters
BITSTRING_SIZE = 32
EPOCHS = 6000
MINIMIZE_FITNESS = True
HYPERPARAMETER_SEARCH = False
MOD_DRAW_FITNESS = 1

# Tunable hyper-parameters
POPULATION_SIZE = 150
CHILDREN = 1
CROSSOVER_PROB = 0.8
MUTATION_PROB = 0.02

